spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/session
    username: session
    password: session
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect