luna:
  open-ai:
    completions-url: "https://api.openai.com/v1/chat/completions"
    images-url: "https://api.openai.com/v1/images/generations"
    embeddings-url: "https://api.openai.com/v1/embeddings"
    image-description-url: "https://api.openai.com/v1/dalle"
    transcription-url: "https://api.openai.com/v1/audio/transcriptions"
    api-key: "${OPENAI_API_KEY}"